language: java

before_install:
- cd BuildTools
- bash build.sh
- cd ../

install:
- mvn -U clean install

script:
- mvn package -DskipTests

cache:
  directories:
  - $HOME/.m2
  - BuildTools/Bukkit
  - BuildTools/Spigot
  - BuildTools/CraftBukkit
  - BuildTools/BuildData

before-deploy:
- export FOO=$(ls Server/plugins/ChestsPlusPlus-*.jar)

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: QyDdKC06atxxu2cJaLwhVr1nAx0oSpch32dPobhy4V4D3Q4CiUa2MGvSNVlzMTmlQWa7BAMB+871A/oZDBx/QcuEa6jGUJuQsnRu/kopMuakHnm3wwK6g91hvOF6XOkBtM/Io4hAIWdrKq+twggQOgu3H0SxmP3pY9Ly0ejod9FkGbN/Q5CoLAgHVc/W5Ktp9x5ylYGAC9t1lXDa+Q7h7SOTW/uecdTOR8SDwiatvsEXy1TNVc+dVin6DrsGnySmlY6OUF9fkhWO0zON3e8l4jvDUaVxOzRC2eFZ3p6QSvO/pd+NyMrBdwHZVKivDIzJM1Zt+8MjNC5dK5LaMNZBIjr9gRZVlLZzxfGqg+jXCn43PF/a08o3CZVGyBcK2tdX8GnXP7aYH7ij7gsEEctRJB6aDQQ4Wr2vGXDglCqNAMSKTSLUCHBqAGtkA6D8Q2eUdl1UBDADDole1ouV8O3yVFF7hy9d+R1Gkla4TIU+RyB9KaWQvuzQT9IpkFFNJJJdkj/qTVqwpx/h824e6KyDrE1fn2qIAHDZCBVCxi+uXYmhhzE9ZCcpgbQKWhZTS9NRoWyDtJEd6cMcgzoFH3cJwmRQFkYl/q8alROFLQTdupB2EpHajSQSuf0+h1GXD4BQwHJ2RAtqs0st//za5AsxcRRQRvs9MJdQuIuixzcnrsc=
  file: "${FOO}"
  on:
    tags: true
    repo: JamesPeters98/ChestsPlusPlus
