  language: java

  before_deploy:
    - "mvn -DskipTests package"
    - export FOO=$(ls target/ChestsPlusPlus-*.jar)

  deploy:
    provider: releases
    github-token: $GITHUB_TOKEN
      file: "${FOO}"
    skip_cleanup: true
    on:
      tags: true
