name: ChestsPlusPlus
version: 1.14.4-v1
main: com.jamesdpeters.minecraft.chests.ChestsPlusPlus
api-version: "1.14"

depend: [ProtocolLib]

commands:
  chestlink:
    description: Chest++ Commands.
    usage: Use /chestlink help for more info.