name: ChestsPlusPlus
version: 1.14.4-v1
main: com.jamesdpeters.minecraft.chests.ChestsPlusPlus
api-version: "1.14"

commands:
  chestlink:
    description: Chest++ Commands.
    usage: Use /chestlink help for more info.

permissions:
  chestlink.*:
    description: Gives permission for all ChestLink commands.
    default: op
    children:
      chestlink.add: true
      chestlink.open: true
      chestlink.menu: true
      chestlink.remove : true
      chestlink.openall: true
      chestlink.addmember: true
  chestlink.add:
    description: Gives permission to add ChestLinks!
    default: true
  chestlink.open:
    description: Gives permission to open ChestLinks!
    default: true
  chestlink.menu:
    description: Gives permission to open the ChestLink menu!
    default: true
  chestlink.remove:
    description: Gives permission to remove a ChestLink!
    default: false
  chestlink.openall:
    description: Gives permission to open all chests, for admin use.
    default: false
chestlink.member:
    description: Gives permission to add/remove a member to/from their chestlink.
    default: true